name: Deploy MultiDocker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'feature/**'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-react -f Dockerfile.dev .
    - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/docker-react npm test

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
    
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with: 
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react
        environment_name: Dockerreact-env
        existing_bucket_name: elasticbeanstalk-us-east-1-741433814378
        region: us-east-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
